const allDestinations = [
    // --- INDIAN DESTINATIONS ---
    { name: "Agra, India", price: 7, category: "India", airport: "Kheria Airport (AGR)", railway: "Agra Cantt (AGC)" },
    { name: "Goa, India", price: 3, category: "India", airport: "Dabolim Airport (GOI)", railway: "Madgaon Junction (MAO)" },
    { name: "Kerala, India", price: 10, category: "India", airport: "Cochin International Airport (COK)", railway: "Ernakulam Junction (ERS)" },
    { name: "Kashmir, India", price: 5, category: "India", airport: "Sheikh Ul-Alam Airport (SXR)", railway: "Jammu Tawi (JAT)" },
    { name: "Rajasthan (Jaipur), India", price: 10, category: "India", airport: "Jaipur International Airport (JAI)", railway: "Jaipur Junction (JP)" },
    { name: "Manali, India", price: 5, category: "India", airport: "Kullu Manali Airport (KUU)", railway: "Joginder Nagar (JDNX)" },
    { name: "Shimla, India", price: 6, category: "India", airport: "Shimla Airport (SLV)", railway: "Kalka (KLK)" },
    { name: "Leh-Ladakh, India", price: 5, category: "India", airport: "Kushok Bakula Rimpochee Airport (IXL)", railway: "Jammu Tawi (JAT)" },
    { name: "Varanasi, India", price: 5, category: "India", airport: "Lal Bahadur Shastri Airport (VNS)", railway: "Varanasi Junction (BSB)" },
    { name: "Darjeeling, India", price: 6, category: "India", airport: "Bagdogra Airport (IXB)", railway: "New Jalpaiguri (NJP)" },
    { name: "Ooty, India", price: 10, category: "India", airport: "Coimbatore International Airport (CJB)", railway: "Mettupalayam (MTP)" },
    { name: "Munnar, India", price: 4, category: "India", airport: "Cochin International Airport (COK)", railway: "Aluva (AWY)" },
    { name: "Udaipur, India", price: 5, category: "India", airport: "Maharana Pratap Airport (UDR)", railway: "Udaipur City (UDZ)" },
    { name: "Jaisalmer, India", price: 7, category: "India", airport: "Jaisalmer Airport (JSA)", railway: "Jaisalmer (JSM)" },
    { name: "Rishikesh, India", price: 8, category: "India", airport: "Jolly Grant Airport (DED)", railway: "Yog Nagari Rishikesh (YNRK)" },
    { name: "Haridwar, India", price: 7, category: "India", airport: "Jolly Grant Airport (DED)", railway: "Haridwar (HW)" },
    { name: "Mussoorie, India", price: 1, category: "India", airport: "Jolly Grant Airport (DED)", railway: "Dehradun (DDN)" },
    { name: "Nainital, India", price: 1, category: "India", airport: "Pantnagar Airport (PGH)", railway: "Kathgodam (KGM)" },
    { name: "Amritsar, India", price: 9, category: "India", airport: "Sri Guru Ram Dass Jee Airport (ATQ)", railway: "Amritsar Junction (ASR)" },
    { name: "Chandigarh, India", price: 6, category: "India", airport: "Shaheed Bhagat Singh Airport (IXC)", railway: "Chandigarh Junction (CDG)" },
    { name: "Mysore, India", price: 9, category: "India", airport: "Mysore Airport (MYQ)", railway: "Mysore Junction (MYS)" },
    { name: "Coorg, India", price: 2, category: "India", airport: "Kannur International Airport (CNN)", railway: "Mysore Junction (MYS)" },
    { name: "Hampi, India", price: 10, category: "India", airport: "Jindal Vijaynagar Airport (VDY)", railway: "Hospet Junction (HPT)" },
    { name: "Bangalore, India", price: 8, category: "India", airport: "Kempegowda International Airport (BLR)", railway: "KSR Bengaluru (SBC)" },
    { name: "Hyderabad, India", price: 9, category: "India", airport: "Rajiv Gandhi International Airport (HYD)", railway: "Secunderabad Junction (SC)" },
    { name: "Chennai, India", price: 8, category: "India", airport: "Chennai International Airport (MAA)", railway: "Chennai Central (MAS)" },
    { name: "Pondicherry, India", price: 10, category: "India", airport: "Pondicherry Airport (PNY)", railway: "Puducherry (PDY)" },
    { name: "Kodaikanal, India", price: 1, category: "India", airport: "Madurai Airport (IXM)", railway: "Kodai Road (KQN)" },
    { name: "Rameshwaram, India", price: 9, category: "India", airport: "Madurai Airport (IXM)", railway: "Rameswaram (RMM)" },
    { name: "Madurai, India", price: 7, category: "India", airport: "Madurai Airport (IXM)", railway: "Madurai Junction (MDU)" },
    { name: "Kanyakumari, India", price: 8, category: "India", airport: "Trivandrum International Airport (TRV)", railway: "Kanyakumari (CAPE)" },
    { name: "Alleppey, India", price: 1, category: "India", airport: "Cochin International Airport (COK)", railway: "Alappuzha (ALLP)" },
    { name: "Kochi, India", price: 2, category: "India", airport: "Cochin International Airport (COK)", railway: "Ernakulam Junction (ERS)" },
    { name: "Wayanad, India", price: 3, category: "India", airport: "Calicut International Airport (CCJ)", railway: "Kozhikode (CLT)" },
    { name: "Andaman Islands, India", price: 3, category: "India", airport: "Veer Savarkar Airport (IXZ)", railway: "Chennai Central (MAS)" }, // No direct rail
    { name: "Lakshadweep, India", price: 4, category: "India", airport: "Agatti Airport (AGX)", railway: "Ernakulam Junction (ERS)" }, // No direct rail
    { name: "Mount Abu, India", price: 9, category: "India", airport: "Maharana Pratap Airport (UDR)", railway: "Abu Road (ABR)" },
    { name: "Jodhpur, India", price: 4, category: "India", airport: "Jodhpur Airport (JDH)", railway: "Jodhpur Junction (JU)" },
    { name: "Khajuraho, India", price: 1, category: "India", airport: "Khajuraho Airport (HJR)", railway: "Khajuraho (KURJ)" },
    { name: "Ujjain, India", price: 7, category: "India", airport: "Devi Ahilya Bai Holkar Airport (IDR)", railway: "Ujjain Junction (UJN)" },

    // --- INTERNATIONAL DESTINATIONS ---
    { name: "Dubai, UAE", price: 75, category: "International", airport: "Dubai International Airport (DXB)", railway: "N/A" },
    { name: "Paris, France", price: 145, category: "International", airport: "Charles de Gaulle Airport (CDG)", railway: "Gare du Nord" },
    { name: "Maldives", price: 125, category: "International", airport: "Velana International Airport (MLE)", railway: "N/A" },
    { name: "Switzerland", price: 185, category: "International", airport: "Zurich Airport (ZRH)", railway: "Zurich HB" },
    { name: "London, UK", price: 165, category: "International", airport: "Heathrow Airport (LHR)", railway: "King's Cross Station" },
    { name: "Tokyo, Japan", price: 135, category: "International", airport: "Narita International Airport (NRT)", railway: "Tokyo Station" },
    { name: "Singapore", price: 85, category: "International", airport: "Changi Airport (SIN)", railway: "N/A" },
    { name: "Bali, Indonesia", price: 65, category: "International", airport: "Ngurah Rai International Airport (DPS)", railway: "N/A" },
    { name: "Amsterdam, Netherlands", price: 125, category: "International", airport: "Schiphol Airport (AMS)", railway: "Amsterdam Centraal" },
    { name: "New York, USA", price: 195, category: "International", airport: "John F. Kennedy Airport (JFK)", railway: "Penn Station" },
    { name: "Sydney, Australia", price: 175, category: "International", airport: "Kingsford Smith Airport (SYD)", railway: "Central Station" },
    { name: "Rome, Italy", price: 115, category: "International", airport: "Leonardo da Vinci International Airport (FCO)", railway: "Roma Termini" },
    { name: "Bangkok, Thailand", price: 45, category: "International", airport: "Suvarnabhumi Airport (BKK)", railway: "Hua Lamphong" },
    { name: "Istanbul, Turkey", price: 95, category: "International", airport: "Istanbul Airport (IST)", railway: "Sirkeci Station" },
    { name: "Cairo, Egypt", price: 85, category: "International", airport: "Cairo International Airport (CAI)", railway: "Ramses Station" },
    { name: "Cape Town, South Africa", price: 135, category: "International", airport: "Cape Town International Airport (CPT)", railway: "Cape Town Station" },
    { name: "Barcelona, Spain", price: 110, category: "International", airport: "El Prat Airport (BCN)", railway: "Barcelona Sants" },
    { name: "Venice, Italy", price: 130, category: "International", airport: "Marco Polo Airport (VCE)", railway: "Venezia Santa Lucia" },
    { name: "Mauritius", price: 90, category: "International", airport: "Sir Seewoosagur Ramgoolam Airport (MRU)", railway: "N/A" },
    { name: "Seychelles", price: 110, category: "International", airport: "Seychelles International Airport (SEZ)", railway: "N/A" },
    { name: "Lisbon, Portugal", price: 105, category: "International", airport: "Humberto Delgado Airport (LIS)", railway: "Lisboa Oriente" },
    { name: "Oslo, Norway", price: 155, category: "International", airport: "Oslo Airport (OSL)", railway: "Oslo Central Station" },
    { name: "Stockholm, Sweden", price: 150, category: "International", airport: "Arlanda Airport (ARN)", railway: "Stockholm Central Station" },
    { name: "Helsinki, Finland", price: 145, category: "International", airport: "Helsinki Airport (HEL)", railway: "Helsinki Central Station" },
    { name: "Reykjavik, Iceland", price: 175, category: "International", airport: "Keflavík International Airport (KEF)", railway: "N/A" },
    { name: "Moscow, Russia", price: 120, category: "International", airport: "Sheremetyevo Airport (SVO)", railway: "Leningradsky Station" },
    { name: "Prague, Czech Republic", price: 95, category: "International", airport: "Václav Havel Airport (PRG)", railway: "Prague Main Station" },
    { name: "Vienna, Austria", price: 115, category: "International", airport: "Vienna International Airport (VIE)", railway: "Vienna Central Station" },
    { name: "Budapest, Hungary", price: 90, category: "International", airport: "Ferenc Liszt Airport (BUD)", railway: "Budapest Keleti" },
    { name: "Hong Kong", price: 80, category: "International", airport: "Hong Kong International Airport (HKG)", railway: "West Kowloon" },
    { name: "Macau", price: 75, category: "International", airport: "Macau International Airport (MFM)", railway: "N/A" },
    { name: "Kuala Lumpur, Malaysia", price: 55, category: "International", airport: "Kuala Lumpur International Airport (KUL)", railway: "KL Sentral" },
    { name: "Ho Chi Minh City, Vietnam", price: 50, category: "International", airport: "Tan Son Nhat International Airport (SGN)", railway: "Saigon Station" },
    { name: "Siem Reap, Cambodia", price: 45, category: "International", airport: "Siem Reap International Airport (REP)", railway: "N/A" },
    { name: "Seoul, South Korea", price: 110, category: "International", airport: "Incheon International Airport (ICN)", railway: "Seoul Station" },
    { name: "Beijing, China", price: 95, category: "International", airport: "Beijing Capital International Airport (PEK)", railway: "Beijing South" },
    { name: "Taipei, Taiwan", price: 85, category: "International", airport: "Taoyuan International Airport (TPE)", railway: "Taipei Main Station" },
    { name: "Manila, Philippines", price: 60, category: "International", airport: "Ninoy Aquino International Airport (MNL)", railway: "Tutuban Station" },
    { name: "Auckland, New Zealand", price: 180, category: "International", airport: "Auckland Airport (AKL)", railway: "Britomart Transport Centre" },
    { name: "Rio de Janeiro, Brazil", price: 160, category: "International", airport: "Galeão International Airport (GIG)", railway: "Central do Brasil" }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = allDestinations;
}
