const packageData = [
  // 1-5. HONEYMOON
  {
    id: 1,
    category: "honeymoon",
    name: "Bora Bora - Romantic Lagoon Escape",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "French Polynesia",
    itinerary: ["Day 1: Arrival & Sunset Boat", "Day 2: Lagoon Snorkel", "Day 3: Overwater Spa", "Day 4: Private Island Picnic", "Day 5: Departure"],
    transport: "Private Boat",
    stay: "Overwater Villa",
    meals: "Fine Dining",
    activities: "Lagoon Tour",
    inclusions: "Honeymoon Kit, Spa",
    exclusions: "Flights",
    price: 325000
  },
  {
    id: 2,
    category: "honeymoon",
    name: "Maldives - Azure Bliss Special",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "Maldives",
    itinerary: ["Day 1: Seaplane Transfer", "Day 2: Reef Dive", "Day 3: Candlelight Dinner", "Day 4: Departure"],
    transport: "Seaplane",
    stay: "Water Villa",
    meals: "All Inclusive",
    activities: "Diving",
    inclusions: "Drink Welcome, Dinner",
    exclusions: "Visa Fees",
    price: 285000
  },
  {
    id: 3,
    category: "honeymoon",
    name: "Santorini - Caldera View Romance",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=600",
    duration: "6 Days / 5 Nights",
    destination: "Greece",
    itinerary: ["Day 1: Oia Sunset", "Day 2: Vine Tour", "Day 3: Sail Boat", "Day 4: Beach Walk", "Day 5: Photo Shoot", "Day 6: Departure"],
    transport: "Private Car",
    stay: "Cave Boutique",
    meals: "Greek Special",
    activities: "Sunset Path",
    inclusions: "Photo Session",
    exclusions: "Alcohol",
    price: 310000
  },
  {
    id: 4,
    category: "honeymoon",
    name: "Venice - Gondola Serenade",
    image: "https://images.unsplash.com/photo-1514890547357-a9ee2887ad8e?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "Italy",
    itinerary: ["Day 1: Canal Ride", "Day 2: Doge's Palace", "Day 3: Murano Glass", "Day 4: Departure"],
    transport: "Water Taxi",
    stay: "Canal Hotel",
    meals: "Italian Buffet",
    activities: "Art History",
    inclusions: "Gondola Pass",
    exclusions: "Tips",
    price: 245000
  },
  {
    id: 5,
    category: "honeymoon",
    name: "Seychelles - Exotic Island Love",
    image: "https://images.unsplash.com/photo-1589979485614-97bad134429b?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Seychelles",
    itinerary: ["Day 1: Beach Relax", "Day 2: Island Hop", "Day 3: Nature Path", "Day 4: Marine Park", "Day 5: Departure"],
    transport: "Ferry & Car",
    stay: "Luxury Resort",
    meals: "Creole Food",
    activities: "Sailing",
    inclusions: "Island Fees",
    exclusions: "Flights",
    price: 298000
  },

  // 6-10. FAMILY
  {
    id: 6,
    category: "family",
    name: "Disneyland Park - Magical Family Fun",
    image: "https://images.unsplash.com/photo-1544084944-15269ec7b5a0?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "Paris / USA",
    itinerary: ["Day 1: Park Entry", "Day 2: Meet Characters", "Day 3: Parade Night", "Day 4: Departure"],
    transport: "Shuttle",
    stay: "Disney Res.",
    meals: "Kids Special",
    activities: "Theme Park",
    inclusions: "Entry Pass",
    exclusions: "Food",
    price: 185000
  },
  {
    id: 7,
    category: "family",
    name: "Eiffel Tower - Paris Highlights",
    image: "https://images.unsplash.com/photo-1543349689-9a4d426bee8e?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "France",
    itinerary: ["Day 1: Seine River Cruise", "Day 2: Eiffel Tower Climb", "Day 3: Louvre Museum", "Day 4: Notre Dame Path", "Day 5: Departure"],
    transport: "Private Van",
    stay: "Pullman Paris",
    meals: "French Pastries",
    activities: "History Tour",
    inclusions: "Car, Guide",
    exclusions: "Flights",
    price: 155000
  },
  {
    id: 8,
    category: "family",
    name: "London Eye - Royal Heritage Tour",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=600",
    duration: "6 Days / 5 Nights",
    destination: "London",
    itinerary: ["Day 1: Arrival & Big Ben", "Day 2: London Eye Flight", "Day 3: Tower of London", "Day 4: Buckingham Palace", "Day 5: Hamleys Shop"],
    transport: "Double Decker Bus",
    stay: "Savoy Hotel",
    meals: "English Breakfast",
    activities: "Sightseeing",
    inclusions: "Oyster Card",
    exclusions: "Dinner",
    price: 172000
  },
  {
    id: 9,
    category: "family",
    name: "Universal Studios - Singapore Adventure",
    image: "https://images.unsplash.com/photo-1516422266298-d4891d40b174?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Singapore",
    itinerary: ["Day 1: Arrival & Sentosa", "Day 2: Theme Park Full Day", "Day 3: Water Park Fun", "Day 4: Night Safari", "Day 5: Departure"],
    transport: "Private Car",
    stay: "Resorts World",
    meals: "Multi-cuisine",
    activities: "Movie Rides",
    inclusions: "Express Pass",
    exclusions: "Meals",
    price: 145000
  },
  {
    id: 10,
    category: "family",
    name: "Gardens by the Bay - Green Singapore",
    image: "https://images.unsplash.com/photo-1595180053272-a7d519283f5e?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "Singapore",
    itinerary: ["Day 1: Supertree Grove", "Day 2: Cloud Forest Dome", "Day 3: Marina Bay Sands", "Day 4: Shopping", "Day 5: Departure"],
    transport: "Local MRT",
    stay: "Marina Bay Sands",
    meals: "Signature Dining",
    activities: "Nature Walk",
    inclusions: "Entry Pass",
    exclusions: "Flights",
    price: 168000
  },

  // 11-15. SOLO
  {
    id: 11,
    category: "solo",
    name: "Bali - Soul Searching Journey",
    image: "https://images.unsplash.com/photo-1518548419970-58e3b40e950d?q=80&w=600",
    duration: "7 Days / 6 Nights",
    destination: "Indonesia",
    itinerary: ["Day 1: Ubud Arrival", "Day 2: Yoga Session", "Day 3: Waterfall Hike", "Day 4: Beach Club", "Day 5: Temple Visit", "Day 6: Rice Field", "Day 7: Departure"],
    transport: "Scooter / Cab",
    stay: "Boutique Villa",
    meals: "Organic Balinese",
    activities: "Meditation, Surf",
    inclusions: "Yoga Pass",
    exclusions: "Alcohol",
    price: 115000
  },
  {
    id: 12,
    category: "solo",
    name: "Bangkok - City Lights Adventure",
    image: "https://images.unsplash.com/photo-1549111298-091f0e495fdb?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Thailand",
    itinerary: ["Day 1: Arrival & Tuk-Tuk", "Day 2: Grand Palace Tour", "Day 3: Floating Market", "Day 4: Sky Bar View", "Day 5: Shopping"],
    transport: "Local Metro",
    stay: "Social Hostel",
    meals: "Street Food Tours",
    activities: "Exploring",
    inclusions: "Tour Guide",
    exclusions: "Bar Tabs",
    price: 38000
  },
  {
    id: 13,
    category: "solo",
    name: "Tokyo - Urban Explorer",
    image: "https://images.unsplash.com/photo-1540959733332-e9ab65ba61c0?q=80&w=600",
    duration: "6 Days / 5 Nights",
    destination: "Japan",
    itinerary: ["Day 1: Akihabara Tech", "Day 2: Shibuya Crossing", "Day 3: Imperial Palace", "Day 4: Harajuku Style", "Day 5: Departure"],
    transport: "Suica Card",
    stay: "Capsule & Pod",
    meals: "Ramen & Sushi",
    activities: "Gaming, Art",
    inclusions: "Rail Pass",
    exclusions: "Food",
    price: 98000
  },
  {
    id: 14,
    category: "solo",
    name: "Barcelona - Gaudi & Giggles",
    image: "https://images.unsplash.com/photo-1583997051654-af6caac09746?q=80&w=600",
    duration: "7 Days / 6 Nights",
    destination: "Spain",
    itinerary: ["Day 1: Las Ramblas Walk", "Day 2: Sagrada Familia", "Day 3: Park Guell", "Day 4: Beach Day", "Day 5: Tapas Crawl"],
    transport: "Bike Rental",
    stay: "Artistic Hostel",
    meals: "Tapas Included",
    activities: "Architecture",
    inclusions: "Museum Pass",
    exclusions: "Flights",
    price: 115000
  },
  {
    id: 15,
    category: "solo",
    name: "Amsterdam - Canal Life",
    image: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Netherlands",
    itinerary: ["Day 1: Canal Cruise", "Day 2: Van Gogh Museum", "Day 3: Bike Around Town", "Day 4: Flower Market", "Day 5: Departure"],
    transport: "Bicycle",
    stay: "Trendy Hostel",
    meals: "Breakfast Only",
    activities: "Biking",
    inclusions: "Bike Rental",
    exclusions: "Dinner",
    price: 85000
  },

  // 16-20. WILDLIFE
  {
    id: 16,
    category: "wildlife",
    name: "Masai Mara - Great Migration Safari",
    image: "https://images.unsplash.com/photo-1516422266298-d4891d40b174?q=80&w=600",
    duration: "6 Days / 5 Nights",
    destination: "Kenya",
    itinerary: ["Day 1: Nairobi Brief", "Day 2: Mara Drive", "Day 3: River Crossing", "Day 4: Hot Air Balloon", "Day 5: Culture Day", "Day 6: Departure"],
    transport: "4x4 Jeep",
    stay: "Luxury Tented Camp",
    meals: "Bush Dinners",
    activities: "Game Drive",
    inclusions: "Park Fees, Jeep",
    exclusions: "Balloon Ride",
    price: 245000
  },
  {
    id: 17,
    category: "wildlife",
    name: "Serengeti - Endless Plains Safari",
    image: "https://images.unsplash.com/photo-1516422266298-d4891d40b174?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Tanzania",
    itinerary: ["Day 1: Arusha Entry", "Day 2: Central Serengeti", "Day 3: Big Five Path", "Day 4: Ngorongoro Crater", "Day 5: Departure"],
    transport: "Safari Van",
    stay: "Savanna Lodge",
    meals: "Full Board",
    activities: "Wildlife Spotting",
    inclusions: "Game Drive Fees",
    exclusions: "Tips",
    price: 215000
  },
  {
    id: 18,
    category: "wildlife",
    name: "Kruger - Big Five Expedition",
    image: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "South Africa",
    itinerary: ["Day 1: Game Viewing", "Day 2: Night Safari", "Day 3: Bush Walk", "Day 4: Departure"],
    transport: "Open Vehicle",
    stay: "Safari Lodge",
    meals: "Boma Dinner",
    activities: "Safari",
    inclusions: "Guide, Meals",
    exclusions: "Alcohol",
    price: 185000
  },
  {
    id: 19,
    category: "wildlife",
    name: "Amazon Rainforest - Jungle Deep Dive",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600",
    duration: "7 Days / 6 Nights",
    destination: "Brazil",
    itinerary: ["Day 1: Manaus Boat", "Day 2: Canopy Walk", "Day 3: Piranha Fish", "Day 4: Night Trek", "Day 5: Local Village", "Day 6: Departure"],
    transport: "Canoe & Hike",
    stay: "Eco Lodge",
    meals: "Tropical Diet",
    activities: "Nature Trail",
    inclusions: "Full Guide",
    exclusions: "Meds",
    price: 265000
  },
  {
    id: 20,
    category: "wildlife",
    name: "Yellowstone - Geyser & Grizzly Tour",
    image: "https://images.unsplash.com/photo-1533094602577-198d3beba81d?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "USA",
    itinerary: ["Day 1: Old Faithful", "Day 2: Canyon Path", "Day 3: Wolf Spotting", "Day 4: Mammoth Springs", "Day 5: Departure"],
    transport: "Private SUV",
    stay: "National Lodge",
    meals: "American Local",
    activities: "Hiking, Views",
    inclusions: "Park Entry Lib",
    exclusions: "Lunch",
    price: 145000
  },

  // 21-25. SPIRITUAL
  {
    id: 21,
    category: "spiritual",
    name: "Kashi Vishwanath - Divine Ganga Tour",
    image: "https://images.unsplash.com/photo-1561361513-39d67566270b?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "India",
    itinerary: ["Day 1: Arrival & Aarti", "Day 2: Temple Darshan", "Day 3: Sarnath Trip", "Day 4: Boat Ride & Exit"],
    transport: "E-Rickshaw & Car",
    stay: "Heritage Ghat Hotel",
    meals: "Satvik Food",
    activities: "Ritual, Prayer",
    inclusions: "VIP Aarti Pass",
    exclusions: "Personal Gift",
    price: 25000
  },
  {
    id: 22,
    category: "spiritual",
    name: "Golden Temple - Serene Amritsar",
    image: "https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "India",
    itinerary: ["Day 1: Temple Visit", "Day 2: Wagah Border", "Day 3: Local Food Path"],
    transport: "AC Cab",
    stay: "4 Star Hotel",
    meals: "Langar & Punjabi",
    activities: "Devotion, Walk",
    inclusions: "Guide, Meals",
    exclusions: "Tips",
    price: 18000
  },
  {
    id: 23,
    category: "spiritual",
    name: "Mecca - Holy Umrah Journey",
    image: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?q=80&w=600",
    duration: "10 Days / 9 Nights",
    destination: "Saudi Arabia",
    itinerary: ["Day 1: Arrival Jeddah", "Day 2: Tawaf Ritual", "Day 3: Prayer in Haram", "Day 4: Ziyarat Tour", "Day 5: Departure"],
    transport: "Luxury Coach",
    stay: "Clock Tower Hotel",
    meals: "Half Board",
    activities: "Religious Path",
    inclusions: "Visa, Hotel",
    exclusions: "Flight",
    price: 195000
  },
  {
    id: 24,
    category: "spiritual",
    name: "Vatican City - Catholic Heritage",
    image: "https://images.unsplash.com/photo-1533050487297-09b450131914?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "Italy / Vatican",
    itinerary: ["Day 1: St. Peter's Basil", "Day 2: Vatican Museum", "Day 3: Sistine Chapel", "Day 4: Garden Walk"],
    transport: "Metro / Walking",
    stay: "Religious Guest House",
    meals: "Simple Italian",
    activities: "History, Prayer",
    inclusions: "Entry Tickets",
    exclusions: "Dinner",
    price: 85000
  },
  {
    id: 25,
    category: "spiritual",
    name: "Bodh Gaya - Path of Enlightenment",
    image: "https://images.unsplash.com/photo-1544885935-98dd03b0c73d?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "India",
    itinerary: ["Day 1: Mahabodhi Temple", "Day 2: Bodhi Tree Med", "Day 3: Monasteries Tour", "Day 4: Local Village", "Day 5: Departure"],
    transport: "Tuk-Tuk",
    stay: "Peace Retreat",
    meals: "Vegetarian",
    activities: "Meditation",
    inclusions: "Session Fees",
    exclusions: "Meds",
    price: 32000
  },

  // 26-30. LUXURY
  {
    id: 26,
    category: "luxury",
    name: "Burj Khalifa - Living in the Clouds",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "Dubai",
    itinerary: ["Day 1: VIP Limousine", "Day 2: Burj Khalifa Top", "Day 3: Yacht Party", "Day 4: Farewell Dinner"],
    transport: "Limousine",
    stay: "Armani Hotel",
    meals: "Michelin Dining",
    activities: "Sky View, Yacht",
    inclusions: "Gold Drinks, Butler",
    exclusions: "Flights",
    price: 450000
  },
  {
    id: 27,
    category: "luxury",
    name: "Palm Jumeirah - Island Paradise",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Dubai",
    itinerary: ["Day 1: Private Jet Arrival", "Day 2: Atlantis Fun", "Day 3: Beach Relax", "Day 4: Desert Safari Luxe", "Day 5: Departure"],
    transport: "Rolls Royce",
    stay: "Royal Atlantis",
    meals: "Seafood Galore",
    activities: "Water Park, Spa",
    inclusions: "Private Cabana",
    exclusions: "Shopping",
    price: 520000
  },
  {
    id: 28,
    category: "luxury",
    name: "Monaco - Elite Riviera Magic",
    image: "https://images.unsplash.com/photo-1533050487297-09b450131914?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "Monaco",
    itinerary: ["Day 1: Casino Visit", "Day 2: Yacht Tour", "Day 3: Grand Prix Track", "Day 4: Departure"],
    transport: "Ferrari Rental",
    stay: "Hotel de Paris",
    meals: "French Fine Dine",
    activities: "Gaming, Sailing",
    inclusions: "Casino Vouchers",
    exclusions: "Tips",
    price: 680000
  },
  {
    id: 29,
    category: "luxury",
    name: "Lake Como - Italian Elegance",
    image: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?q=80&w=600",
    duration: "6 Days / 5 Nights",
    destination: "Italy",
    itinerary: ["Day 1: Villa Tour", "Day 2: Private Cruise", "Day 3: Cooking Class", "Day 4: Bellagio Trail", "Day 5: Luxury Spa"],
    transport: "Classic Alfa Romeo",
    stay: "Villa d'Este",
    meals: "Gourmet Pasta",
    activities: "Lakeside Life",
    inclusions: "Boat Hire",
    exclusions: "Drinks",
    price: 590000
  },
  {
    id: 30,
    category: "luxury",
    name: "Swiss Alps - Winter Wonderland",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Switzerland",
    itinerary: ["Day 1: Heli Arrival", "Day 2: Skiing Day", "Day 3: Chocolate Shop", "Day 4: Mount Titlis", "Day 5: Departure"],
    transport: "Helicopter",
    stay: "Grand Hotel Zermatt",
    meals: "Fondue & Wine",
    activities: "Skiing, Fly",
    inclusions: "Ski Pass, Heli",
    exclusions: "Equipment",
    price: 720000
  },

  // 31-35. BUDGET
  {
    id: 31,
    category: "budget",
    name: "Goa - Sun, Sand & Savings",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "India",
    itinerary: ["Day 1: Beach Relax", "Day 2: North Goa Forts", "Day 3: Water Sports", "Day 4: Departure"],
    transport: "Scooter / Cab",
    stay: "3 Star Resort",
    meals: "Seafood Thali",
    activities: "Beach Fun",
    inclusions: "Breakfast, Stay",
    exclusions: "Dinner",
    price: 15000
  },
  {
    id: 32,
    category: "budget",
    name: "Kathmandu - Cultural Budget Trip",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Nepal",
    itinerary: ["Day 1: Arrival Thamel", "Day 2: Swayambhu Hike", "Day 3: Patan Durbar", "Day 4: local Market", "Day 5: Departure"],
    transport: "Local Bus",
    stay: "Guesthouse",
    meals: "Dal Bhat Power",
    activities: "Temples",
    inclusions: "Breakfast",
    exclusions: "Flights",
    price: 18000
  },
  {
    id: 33,
    category: "budget",
    name: "Sri Lanka - Coastal Island Hopper",
    image: "https://images.unsplash.com/photo-1525625232757-0740664687d6?q=80&w=600",
    duration: "6 Days / 5 Nights",
    destination: "Sri Lanka",
    itinerary: ["Day 1: Colombo Walk", "Day 2: Kandy Temple", "Day 3: Tea Gardens", "Day 4: Galle Beach", "Day 5: Departure"],
    transport: "Train & Tutu",
    stay: "Budget Villa",
    meals: "Curry & Rice",
    activities: "Train Ride",
    inclusions: "All Rail",
    exclusions: "Visa",
    price: 32000
  },
  {
    id: 34,
    category: "budget",
    name: "Bangkok - Street Food & Markets",
    image: "https://images.unsplash.com/photo-1549111298-091f0e495fdb?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Thailand",
    itinerary: ["Day 1: Khao San Road", "Day 2: Chatuchak Market", "Day 3: Canal Tour", "Day 4: MBK Shopping", "Day 5: Departure"],
    transport: "BTS & Van",
    stay: "Budget Hotel",
    meals: "Street Food Tours",
    activities: "Local Exploring",
    inclusions: "Metro Pass",
    exclusions: "Insurance",
    price: 28000
  },
  {
    id: 35,
    category: "budget",
    name: "Bali - Backpacker's Paradize",
    image: "https://images.unsplash.com/photo-1518548419970-58e3b40e950d?q=80&w=600",
    duration: "6 Days / 5 Nights",
    destination: "Indonesia",
    itinerary: ["Day 1: Kuta Beach", "Day 2: Ubud Market", "Day 3: Tegenungan Fall", "Day 4: Tanah Lot", "Day 5: Departure"],
    transport: "Shared Shuttle",
    stay: "Homestay Stay",
    meals: "Nasi Goreng Thali",
    activities: "Sightseeing",
    inclusions: "Car & Driver",
    exclusions: "All Entry",
    price: 25000
  },

  // 36-40. GROUP
  {
    id: 36,
    category: "group",
    name: "Dubai Marina - Party Boat Crew",
    image: "https://images.unsplash.com/photo-1544837303-a16f3938becc?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "Dubai",
    itinerary: ["Day 1: Arrival Party", "Day 2: Marina Cruise", "Day 3: JBR Beach Fun", "Day 4: Departure"],
    transport: "Shared Coach",
    stay: "Premium Hostel",
    meals: "Group BBQ Dine",
    activities: "Cruising, Dance",
    inclusions: "Boat Entry, Music",
    exclusions: "Drinks",
    price: 48000
  },
  {
    id: 37,
    category: "group",
    name: "Desert Safari - Dune Bashing Crew",
    image: "https://images.unsplash.com/photo-1544837303-a16f3938becc?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "Dubai",
    itinerary: ["Day 1: 4x4 Dune Bashing", "Day 2: Camel Riding", "Day 3: Belly Dance Show", "Day 4: Departure"],
    transport: "4x4 SUV",
    stay: "Desert Camp Luxe",
    meals: "Arabic Buffet",
    activities: "Safari",
    inclusions: "All Transport",
    exclusions: "Quad Bike",
    price: 42000
  },
  {
    id: 38,
    category: "group",
    name: "Burj Khalifa - Top of the World Group",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=600",
    duration: "2 Days / 1 Night",
    destination: "Dubai",
    itinerary: ["Day 1: Observation Deck", "Day 2: Fountain Show", "Day 3: Group Dinner"],
    transport: "Shared Coach",
    stay: "Downtown Hotel",
    meals: "Brunch Included",
    activities: "Sightseeing",
    inclusions: "Fast Track",
    exclusions: "Shopping",
    price: 35000
  },
  {
    id: 39,
    category: "group",
    name: "Palm Jumeirah - Island Party Vibe",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "Dubai",
    itinerary: ["Day 1: Water Park Day", "Day 2: Beach Club Night", "Day 3: Yacht Spin"],
    transport: "Party Bus",
    stay: "The Palm Resort",
    meals: "BBQ & Drinks",
    activities: "Watersports",
    inclusions: "Park Access",
    exclusions: "Spa",
    price: 55000
  },
  {
    id: 40,
    category: "group",
    name: "Dubai Mall - Ultimate Shop Group",
    image: "https://images.unsplash.com/photo-1540959733332-e9ab65ba61c0?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "Dubai",
    itinerary: ["Day 1: Mall Marathon", "Day 2: Aquarium Visit", "Day 3: VR Park Fun"],
    transport: "Mall Shuttle",
    stay: "Adjacent Hotel",
    meals: "Food Court Coup",
    activities: "Experiences",
    inclusions: "VR Credit",
    exclusions: "Goods",
    price: 25000
  },

  // 41-45. WEEKEND
  {
    id: 41,
    category: "weekend",
    name: "Munnar - Green Hill Escape",
    image: "https://images.unsplash.com/photo-1582236371583-9366e4811bda?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "India",
    itinerary: ["Day 1: Tea Garden Walk", "Day 2: Lake Boating", "Day 3: Local Market", "Day 4: Departure"],
    transport: "Private Car",
    stay: "Hillside Cottage",
    meals: "Local Kerala",
    activities: "Nature",
    inclusions: "Car, Stay",
    exclusions: "Entry Fees",
    price: 14000
  },
  {
    id: 42,
    category: "weekend",
    name: "Lonavala - Monsoon Bliss",
    image: "https://images.unsplash.com/photo-1593181629936-11c609b8db9b?q=80&w=600",
    duration: "2 Days / 1 Night",
    destination: "India",
    itinerary: ["Day 1: Tiger Point View", "Day 2: Bhusi Dam", "Day 3: Chikki Shopping"],
    transport: "Shared Volvo",
    stay: "Mountain Resort",
    meals: "Breakfast Inc.",
    activities: "Trekking",
    inclusions: "Bus, Hotel",
    exclusions: "All meals",
    price: 8500
  },
  {
    id: 43,
    category: "weekend",
    name: "Mahabaleshwar - Strawberry Trails",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "India",
    itinerary: ["Day 1: Mapro Garden", "Day 2: Arthur's Seat", "Day 3: Venna Lake"],
    transport: "Private Car",
    stay: "Heritage Bungalow",
    meals: "Farm Fresh",
    activities: "Boating",
    inclusions: "Farm Tour",
    exclusions: "Meals",
    price: 12000
  },
  {
    id: 44,
    category: "weekend",
    name: "Coorg - Scotland of India",
    image: "https://images.unsplash.com/photo-1590050752117-23a9d7fc9bb5?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "India",
    itinerary: ["Day 1: Coffee Estate", "Day 2: Abbey Falls", "Day 3: Raja's Seat"],
    transport: "Private Jeep",
    stay: "Coffee Estate Stay",
    meals: "Kodava Food",
    activities: "Plantation Walk",
    inclusions: "Plantation entry",
    exclusions: "Flights",
    price: 15000
  },
  {
    id: 45,
    category: "weekend",
    name: "Ooty - Nilgiri Queen Escape",
    image: "https://images.unsplash.com/photo-1582236371583-9366e4811bda?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "India",
    itinerary: ["Day 1: Toy Train Ride", "Day 2: Botanical Garden", "Day 3: Pykara Lake"],
    transport: "Cabs",
    stay: "Pine View Hotel",
    meals: "South Indian",
    activities: "Toy Train",
    inclusions: "Train Ticket",
    exclusions: "Meals",
    price: 13000
  },

  // 46-50. CULTURAL
  {
    id: 46,
    category: "cultural",
    name: "Kyoto - Zen & Heritage",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Japan",
    itinerary: ["Day 1: Bamboo Forest", "Day 2: Fushimi Inari", "Day 3: Tea Ceremony", "Day 4: Gion Walk", "Day 5: Departure"],
    transport: "JR Rail",
    stay: "Ryokan Stay",
    meals: "Kaiseki Dining",
    activities: "Temple Tour",
    inclusions: "Ritual Entry",
    exclusions: "Flights",
    price: 165000
  },
  {
    id: 47,
    category: "cultural",
    name: "Rome - Eternal City Wonders",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=600",
    duration: "6 Days / 5 Nights",
    destination: "Italy",
    itinerary: ["Day 1: Colosseum Entry", "Day 2: Roman Forum", "Day 3: Trevi Fountain", "Day 4: Pantheon Walk", "Day 5: Pizza Workshop"],
    transport: "Metro Pass",
    stay: "Boutique Rome",
    meals: "Pizza & Pasta",
    activities: "History Tour",
    inclusions: "All Entry",
    exclusions: "Tips",
    price: 142000
  },
  {
    id: 48,
    category: "cultural",
    name: "Athens - Cradle of Civilization",
    image: "https://images.unsplash.com/photo-1503152397458-71280f338f9f?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "Greece",
    itinerary: ["Day 1: Acropolis Tour", "Day 2: Plaka District", "Day 3: Temple of Zeus", "Day 4: National Museum", "Day 5: Departure"],
    transport: "Walking & Bus",
    stay: "Old City Hotel",
    meals: "Greek Salads",
    activities: "History",
    inclusions: "Acropolis pass",
    exclusions: "Lunch",
    price: 128000
  },
  {
    id: 49,
    category: "cultural",
    name: "Varanasi - Living History Tour",
    image: "https://images.unsplash.com/photo-1473163922524-7664e07b20d8?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "India",
    itinerary: ["Day 1: Evening Aarti", "Day 2: Morning Boat", "Day 3: Sarnath Day", "Day 4: Local Arts"],
    transport: "Car & Boat",
    stay: "Ghatside Stay",
    meals: "Street Delights",
    activities: "Prayers",
    inclusions: "Boat Guide",
    exclusions: "Tips",
    price: 22000
  },
  {
    id: 50,
    category: "cultural",
    name: "Cairo - Pharaohs' Legacy",
    image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?q=80&w=600",
    duration: "6 Days / 5 Nights",
    destination: "Egypt",
    itinerary: ["Day 1: Pyramids of Giza", "Day 2: Egyptian Museum", "Day 3: Old Cairo Market", "Day 4: Nile Cruise", "Day 5: Departure"],
    transport: "AC Coach",
    stay: "Nile View Hotel",
    meals: "Arabian Food",
    activities: "Exploration",
    inclusions: "Entry VIP",
    exclusions: "Visa",
    price: 155000
  },

  // 51-55. EDUCATIONAL
  {
    id: 51,
    category: "educational",
    name: "NASA Kennedy Space Center - STEM Camp",
    image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=600",
    duration: "10 Days / 9 Nights",
    destination: "USA",
    itinerary: ["Day 1: Arrival & Brief", "Day 2: Rocket Science 101", "Day 3: Astronaut Meet", "Day 4: Simulation Day", "Day 5: Museum Tour"],
    transport: "Camp Bus",
    stay: "Student Dorms",
    meals: "All Inclusive",
    activities: "Rocket Build",
    inclusions: "Camp Kit",
    exclusions: "Visa",
    price: 295000
  },
  {
    id: 52,
    category: "educational",
    name: "Smithsonian Institution - History & Tech",
    image: "https://images.unsplash.com/photo-1549466600-62cf6afbc43d?q=80&w=600",
    duration: "8 Days / 7 Nights",
    destination: "USA",
    itinerary: ["Day 1: Museum of Art", "Day 2: Air & Space Museum", "Day 3: National Zoo", "Day 4: History Archives", "Day 5: Tech Exhibits"],
    transport: "DC Metro",
    stay: "Student Hostel",
    meals: "Boxed Lunches",
    activities: "Curator Talk",
    inclusions: "Entry Passes",
    exclusions: "Flight",
    price: 245000
  },
  {
    id: 53,
    category: "educational",
    name: "Oxford University - Academic Spirit",
    image: "https://images.unsplash.com/photo-1527631746610-bca00a040d60?q=80&w=600",
    duration: "7 Days / 6 Nights",
    destination: "UK",
    itinerary: ["Day 1: Campus Tour", "Day 2: Library Visit", "Day 3: Debate Workshop", "Day 4: Science Labs", "Day 5: Punting"],
    transport: "Local Bus",
    stay: "College Dorms",
    meals: "College Dining",
    activities: "Lecture Access",
    inclusions: "Dorm, Meals",
    exclusions: "Flights",
    price: 212000
  },
  {
    id: 54,
    category: "educational",
    name: "MIT - Engineering & Future",
    image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=600",
    duration: "6 Days / 5 Nights",
    destination: "USA",
    itinerary: ["Day 1: Robotics Lab", "Day 2: AI Center", "Day 3: Architecture Tour", "Day 4: Physics Demo", "Day 5: Project Pitch"],
    transport: "Boston T",
    stay: "Campus Guesthouse",
    meals: "Bento Boxes",
    activities: "Lab Access",
    inclusions: "T-Pass, Lab",
    exclusions: "Personal",
    price: 280000
  },
  {
    id: 55,
    category: "educational",
    name: "California Science Center - Space Shuttle",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?q=80&w=600",
    duration: "5 Days / 4 Nights",
    destination: "USA",
    itinerary: ["Day 1: Endeavour Exhibit", "Day 2: Ecosystems Tour", "Day 3: Hands-on Lab", "Day 4: IMAX Movie", "Day 5: Hollywood Visit"],
    transport: "Private Coach",
    stay: "Budget Resort",
    meals: "Pizza & Burgers",
    activities: "Science Labs",
    inclusions: "IMAX, Lab",
    exclusions: "Souvenirs",
    price: 195000
  },

  // 56-60. CORPORATE
  {
    id: 56,
    category: "corporate",
    name: "Manali - Peak Team Retreat",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "India",
    itinerary: ["Day 1: Team Building", "Day 2: Strategy Session", "Day 3: Adventure Day", "Day 4: Gala Dinner", "Day 5: Departure"],
    transport: "Luxury Coach",
    stay: "5 Star Resort",
    meals: "Full Board Buffet",
    activities: "Workshops",
    inclusions: "AV Rental",
    exclusions: "Upgrades",
    price: 52000
  },
  {
    id: 57,
    category: "corporate",
    name: "Rishikesh - Riverside Reset",
    image: "https://images.unsplash.com/photo-1621235652591-66df75f7eeab?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "India",
    itinerary: ["Day 1: Yoga & Brief", "Day 2: Rafting & Fun", "Day 3: Camp Fire Night", "Day 4: Departure"],
    transport: "AC Traveler",
    stay: "Luxury Tent Camp",
    meals: "Organic Foods",
    activities: "Adventure",
    inclusions: "Rafting Gear",
    exclusions: "Personal",
    price: 18000
  },
  {
    id: 58,
    category: "corporate",
    name: "Shimla - Colonial Board Meeting",
    image: "https://images.unsplash.com/photo-1549466600-62cf6afbc43d?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "India",
    itinerary: ["Day 1: Meeting Day 1", "Day 2: Ridge Walk", "Day 3: Dinner at Cecil"],
    transport: "SUV",
    stay: "Oberoi Cecil",
    meals: "Fine Dining",
    activities: "Networking",
    inclusions: "Conference Hall",
    exclusions: "Laundry",
    price: 45000
  },
  {
    id: 59,
    category: "corporate",
    name: "Goa - Beachfront Offsite",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=600",
    duration: "4 Days / 3 Nights",
    destination: "India",
    itinerary: ["Day 1: Ice Breakers", "Day 2: Workshop & Party", "Day 3: Water Sports", "Day 4: Departure"],
    transport: "Luxury Bus",
    stay: "W Goa Resort",
    meals: "Seafood & Buffet",
    activities: "Team Games",
    inclusions: "DJ & Drinks",
    exclusions: "Spa",
    price: 65000
  },
  {
    id: 60,
    category: "corporate",
    name: "Nainital - Lakeside Strategy",
    image: "https://images.unsplash.com/photo-1621235652591-66df75f7eeab?q=80&w=600",
    duration: "3 Days / 2 Nights",
    destination: "India",
    itinerary: ["Day 1: Arrival & Brief", "Day 2: Boat Meeting", "Day 3: Cable Car Trip"],
    transport: "Local Cabs",
    stay: "Manu Maharani",
    meals: "Kumaoni Buffet",
    activities: "Bonding",
    inclusions: "WiFi, LCD",
    exclusions: "Flights",
    price: 35000
  },

  // 61-65. CRUISE
  {
    id: 61,
    category: "cruise",
    name: "Antarctic Peninsula - Ice Expedition",
    image: "https://images.unsplash.com/photo-1548574505-5e239809ee19?q=80&w=600",
    duration: "15 Days / 14 Nights",
    destination: "Antarctica",
    itinerary: ["Day 1: Ushuaia Boat", "Day 2: Drake Passage", "Day 3: Iceberg Views", "Day 4: Whale Spotting", "Day 5: Shore Landing"],
    transport: "Ice Ship",
    stay: "Sea cabin Luxe",
    meals: "Gourmet Ships",
    activities: "Lectures",
    inclusions: "Polar Gear",
    exclusions: "Drinks",
    price: 895000
  },
  {
    id: 62,
    category: "cruise",
    name: "Drake Passage - Thrill of the Seas",
    image: "https://images.unsplash.com/photo-1516422266298-d4891d40b174?q=80&w=600",
    duration: "10 Days / 9 Nights",
    destination: "Southern Ocean",
    itinerary: ["Day 1: Buenos Aires", "Day 2: Boarding Quest", "Day 3: Sea Lions Watch", "Day 4: Open Sea Cruising", "Day 5: Return"],
    transport: "Expedition Vessel",
    stay: "Ocean Suite",
    meals: "Seafood Special",
    activities: "Navigation",
    inclusions: "All Landings",
    exclusions: "Gear",
    price: 655000
  },
  {
    id: 63,
    category: "cruise",
    name: "Paradise Bay - Silent Ice World",
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?q=80&w=600",
    duration: "12 Days / 11 Nights",
    destination: "Antarctica",
    itinerary: ["Day 1: Arrival & Deck", "Day 2: Kayak Session", "Day 3: Penguin Colony", "Day 4: Glacial Hike", "Day 5: Bay Cruise"],
    transport: "Small Cruiser",
    stay: "Cabin with View",
    meals: "Buffet Lunch",
    activities: "Kayaking",
    inclusions: "Gear, Guide",
    exclusions: "Polar Plunge",
    price: 785000
  },
  {
    id: 64,
    category: "cruise",
    name: "Deception Island - Volcanic Shores",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=600",
    duration: "11 Days / 10 Nights",
    destination: "Antarctica",
    itinerary: ["Day 1: Hot Springs Dip", "Day 2: Black Sand Walk", "Day 3: Abandoned Whaling", "Day 4: Caldera View", "Day 5: Departure"],
    transport: "Zodiak Boats",
    stay: "Cruiser Stay",
    meals: "Hot Meals",
    activities: "Thermal Bath",
    inclusions: "Safety Gear",
    exclusions: "Insurance",
    price: 710000
  },
  {
    id: 65,
    category: "cruise",
    name: "Lemaire Channel - Photographer's Dream",
    image: "https://images.unsplash.com/photo-1548574505-5e239809ee19?q=80&w=600",
    duration: "13 Days / 12 Nights",
    destination: "Antarctica",
    itinerary: ["Day 1: Sunset Views", "Day 2: Narrow Channel", "Day 3: Portrait Shots", "Day 4: Glacier Backdrop", "Day 5: Farewell"],
    transport: "Luxury Liner",
    stay: "Balcony Cabin",
    meals: "Photography Workshop",
    activities: "Photo Tour",
    inclusions: "Tripod Rent",
    exclusions: "Lens Pro",
    price: 835000
  }
];

export default packageData;
