const allDestinations = [
    { name: "Bora Bora Overwater Romance", price: 345000, category: "Packages", image: "images/packages/honeymoon/bora_bora.jpg" },
    { name: "Maldives Private Island Escape", price: 285000, category: "Packages", image: "images/packages/honeymoon/maldives.jpg" },
    { name: "Santorini Sunset Dreams", price: 215000, category: "Packages", image: "images/packages/honeymoon/santorini.jpg" },
    { name: "Venice Canal Rendezvous", price: 185000, category: "Packages", image: "images/packages/honeymoon/venice.jpg" },
    { name: "Seychelles Tropical Shore", price: 312000, category: "Packages", image: "images/packages/honeymoon/seychelles.jpg" },
    { name: "Disneyland Park Adventure", price: 118000, category: "Packages", image: "images/packages/family/disneyland_park.jpg" },
    { name: "Eiffel Tower & Paris Wonders", price: 139000, category: "Packages", image: "images/packages/family/eiffel_tower.jpg" },
    { name: "London Eye Royal Heritage", price: 148000, category: "Packages", image: "images/packages/family/london_eye.jpg" },
    { name: "Universal Studios Singapore Fun", price: 78500, category: "Packages", image: "images/packages/family/universal_studios_singapore.jpg" },
    { name: "Gardens by the Bay Spectra", price: 52000, category: "Packages", image: "images/packages/family/gardens_by_the_bay.jpg" },
    { name: "Bali Spiritual Quest", price: 65500, category: "Packages", image: "images/packages/solo/bali.jpg" },
    { name: "Bangkok City Explorer", price: 41000, category: "Packages", image: "images/packages/solo/bangkok.jpg" },
    { name: "Tokyo Neon Nights", price: 121000, category: "Packages", image: "images/packages/solo/tokyo.jpg" },
    { name: "Barcelona Art Walk", price: 102000, category: "Packages", image: "images/packages/solo/barcelona.jpg" },
    { name: "Amsterdam Canal Cycling", price: 86000, category: "Packages", image: "images/packages/solo/amsterdam.jpg" },
    { name: "Masai Mara Safari Grand", price: 182000, category: "Packages", image: "images/packages/wildlife/masai_mara_national_reserve.jpg" },
    { name: "Serengeti Great Migration", price: 252000, category: "Packages", image: "images/packages/wildlife/serengeti_national_park.jpg" },
    { name: "Kruger National Park Quest", price: 122000, category: "Packages", image: "images/packages/wildlife/kruger_national_park.jpg" },
    { name: "Amazon Rainforest Expedition", price: 162000, category: "Packages", image: "images/packages/wildlife/amazon_rainforest.jpg" },
    { name: "Yellowstone Geothermal Wildlife", price: 132000, category: "Packages", image: "images/packages/wildlife/yellowstone_national_park.jpg" },
    { name: "Kashi Vishwanath Spiritual Tour", price: 15500, category: "Packages", image: "images/packages/spiritual/kashi_vishwanath_temple.jpg" },
    { name: "Golden Temple Peace Tour", price: 11500, category: "Packages", image: "images/packages/spiritual/golden_temple.jpg" },
    { name: "Holy Mecca Umrah Journey", price: 76000, category: "Packages", image: "images/packages/spiritual/mecca.jpg" },
    { name: "Vatican & Rome Pilgrimage", price: 112000, category: "Packages", image: "images/packages/spiritual/vatican_city.jpg" },
    { name: "Bodh Gaya Zen Awakening", price: 18800, category: "Packages", image: "images/packages/spiritual/bodh_gaya.jpg" },
    { name: "Burj Khalifa Elite Suite", price: 152000, category: "Packages", image: "images/packages/luxury/burj_khalifa.jpg" },
    { name: "Palm Jumeirah Ultra Wealth", price: 191000, category: "Packages", image: "images/packages/luxury/palm_jumeirah.jpg" },
    { name: "Monaco Royal Casino Gala", price: 362000, category: "Packages", image: "images/packages/luxury/monaco.jpg" },
    { name: "Lake Como Celebrity Escape", price: 421000, category: "Packages", image: "images/packages/luxury/lake_como.jpg" },
    { name: "Swiss Alps Ice Palace", price: 489000, category: "Packages", image: "images/packages/luxury/swiss_alps.jpg" },
    { name: "Goa Beach Budget Bash", price: 9200, category: "Packages", image: "images/packages/budget/goa.jpg" },
    { name: "Bangkok Backpackers Dream", price: 21800, category: "Packages", image: "images/packages/budget/bangkok.jpg" },
    { name: "Bali Kuta Fun Surf", price: 23500, category: "Packages", image: "images/packages/budget/bali.jpg" },
    { name: "Kathmandu Valley Quest", price: 12200, category: "Packages", image: "images/packages/budget/kathmandu.jpg" },
    { name: "Sri Lanka Coastal Budget", price: 27900, category: "Packages", image: "images/packages/budget/sri_lanka.jpg" },
    { name: "Dubai Marina Yacht Fiesta", price: 61000, category: "Packages", image: "images/packages/group/dubai_marina.jpg" },
    { name: "Burj Khalifa Group View", price: 47500, category: "Packages", image: "images/packages/group/burj_khalifa.jpg" },
    { name: "Desert Safari Group Adventure", price: 37500, category: "Packages", image: "images/packages/group/desert_safari_dubai.jpg" },
    { name: "Palm Jumeirah Group Splash", price: 71500, category: "Packages", image: "images/packages/group/palm_jumeirah.jpg" },
    { name: "Dubai Mall Shopping Spree", price: 54500, category: "Packages", image: "images/packages/group/dubai_mall.jpg" },
    { name: "Munnar Tea Hill Weekend", price: 8200, category: "Packages", image: "images/packages/weekend/munnar.jpg" },
    { name: "Lonavala Monsoon Retreat", price: 5200, category: "Packages", image: "images/packages/weekend/lonavala.jpg" },
    { name: "Mahabaleshwar Getaway", price: 7400, category: "Packages", image: "images/packages/weekend/mahabaleshwar.jpg" },
    { name: "Coorg Coffee Weekend", price: 9500, category: "Packages", image: "images/packages/weekend/coorg.jpg" },
    { name: "Ooty Heritage Ride", price: 11200, category: "Packages", image: "images/packages/weekend/ooty.jpg" },
    { name: "Kyoto Ancient Heritage", price: 104000, category: "Packages", image: "images/packages/cultural/kyoto.jpg" },
    { name: "Rome Eternal City Tour", price: 134000, category: "Packages", image: "images/packages/cultural/rome.jpg" },
    { name: "Athens Greek Discovery", price: 88000, category: "Packages", image: "images/packages/cultural/athens.jpg" },
    { name: "Varanasi Ghats Cultural", price: 18400, category: "Packages", image: "images/packages/cultural/varanasi.jpg" },
    { name: "Cairo Pharaohs Quest", price: 114000, category: "Packages", image: "images/packages/cultural/cairo.jpg" },
    { name: "NASA Space Center Camp", price: 298000, category: "Packages", image: "images/packages/educational/nasa_kennedy_space_center.jpg" },
    { name: "Smithsonian Science Quest", price: 198000, category: "Packages", image: "images/packages/educational/smithsonian_institution.jpg" },
    { name: "Oxford Heritage Program", price: 428000, category: "Packages", image: "images/packages/educational/oxford_university.jpg" },
    { name: "MIT Tech Exploration", price: 368000, category: "Packages", image: "images/packages/educational/mit.jpg" },
    { name: "California Science Center", price: 178000, category: "Packages", image: "images/packages/educational/california_science_center.jpg" },
    { name: "Manali Leadership Peak", price: 21500, category: "Packages", image: "images/packages/corporate/manali.jpg" },
    { name: "Rishikesh Team Boost", price: 16200, category: "Packages", image: "images/packages/corporate/rishikesh.jpg" },
    { name: "Shimla Executive Summit", price: 28200, category: "Packages", image: "images/packages/corporate/shimla.jpg" },
    { name: "Goa Beach Offsite", price: 24200, category: "Packages", image: "images/packages/corporate/goa.jpg" },
    { name: "Nainital Lakeside Retreat", price: 19200, category: "Packages", image: "images/packages/corporate/nainital.jpg" },
    { name: "Antarctic Peninsula Polar", price: 500000, category: "Packages", image: "images/packages/cruise/antarctic_peninsula.jpg" },
    { name: "Drake Passage Sail Heritage", price: 495000, category: "Packages", image: "images/packages/cruise/drake_passage.jpg" },
    { name: "Paradise Bay Silent Quest", price: 500000, category: "Packages", image: "images/packages/cruise/paradise_bay.jpg" },
    { name: "Deception Island Voyage", price: 500000, category: "Packages", image: "images/packages/cruise/deception_island.jpg" },
    { name: "Lemaire Channel Scenic", price: 500000, category: "Packages", image: "images/packages/cruise/lemaire_channel.jpg" },
];